#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
mix_with_music.py
Combines narration + background music into both final MP4s.

Expects:
  video_output/atlasaudio-music-background-594872.mp3  (Pixabay, AtlasAudio, track 594872)
  video_output/_audio/narration_mix.wav              (generated by add_narration.py)
  video_output/cricket_market_wide_1920x1080.mp4
  video_output/cricket_market_vertical_1080x1920.mp4

Outputs:
  video_output/cricket_market_wide_1920x1080_final.mp4
  video_output/cricket_market_vertical_1080x1920_final.mp4

Music is set ~17 dB below the narration (volume=0.14), with
1.5 s fade-in and 1.5 s fade-out. Video is copied byte-for-byte
(no re-encode). Dimensions and duration are preserved exactly.

Run:
    video_venv/Scripts/python video_output/mix_with_music.py
"""

import sys, os, subprocess, re

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import imageio_ffmpeg
FF = imageio_ffmpeg.get_ffmpeg_exe()

OUTDIR  = os.path.dirname(os.path.abspath(__file__))
MUSIC   = os.path.join(OUTDIR, "atlasaudio-music-background-594872.mp3")
NARR    = os.path.join(OUTDIR, "_audio", "narration_mix.wav")

# Music level relative to narration.
# 0.14 ≈ -17 dB: clearly audible but solidly beneath the voice.
MUSIC_VOLUME = 0.14
FADE_DUR     = 1.5   # seconds for fade-in and fade-out

VIDEOS = [
    ("cricket_market_wide_1920x1080.mp4",     "cricket_market_wide_1920x1080_final.mp4"),
    ("cricket_market_vertical_1080x1920.mp4", "cricket_market_vertical_1080x1920_final.mp4"),
]


def run(cmd):
    return subprocess.run(
        cmd, capture_output=True,
        text=True, encoding="utf-8", errors="replace"
    )


def ff_duration(path):
    r = run([FF, "-i", path, "-f", "null", "-"])
    m = re.search(r"Duration:\s+(\d+):(\d+):([\d.]+)", r.stderr)
    if m:
        return int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3))
    return None


def verify_stream(path):
    r = run([FF, "-i", path, "-f", "null", "-"])
    m = re.search(r"Stream.*Video.*?(\d{3,4})x(\d{3,4})", r.stderr)
    return (int(m.group(1)), int(m.group(2))) if m else (None, None)


def mix(video_in, video_out):
    """
    filter_complex:
      [1:a]  narration (full volume)
      [2:a]  music: trim to 20 s, volume=MUSIC_VOLUME, fade in/out
      amix   sum both; normalize=0 keeps levels as-set
    """
    fade_out_start = 20.0 - FADE_DUR

    fc = (
        f"[2:a]atrim=0:20,"
        f"volume={MUSIC_VOLUME},"
        f"afade=t=in:st=0:d={FADE_DUR},"
        f"afade=t=out:st={fade_out_start}:d={FADE_DUR}"
        f"[music];"
        f"[1:a][music]amix=inputs=2:duration=longest:normalize=0[out]"
    )

    cmd = [
        FF, "-y",
        "-i", video_in,   # 0: silent video
        "-i", NARR,       # 1: narration WAV
        "-i", MUSIC,      # 2: background music MP3
        "-filter_complex", fc,
        "-map", "0:v",    # video from silent source — no re-encode
        "-map", "[out]",
        "-c:v", "copy",
        "-c:a", "aac",
        "-b:a", "192k",
        "-ac", "2",
        "-t", "20",
        video_out,
    ]
    r = run(cmd)
    if r.returncode != 0:
        print(f"  ffmpeg error for {os.path.basename(video_out)}:")
        print(r.stderr[-3000:])
        sys.exit(1)


def main():
    print("=" * 56)
    print("  Cricket Market USA -- Final Mix (narration + music)")
    print("=" * 56)

    # Pre-flight checks
    for path, label in [(MUSIC, "music MP3"), (NARR, "narration WAV")]:
        if not os.path.exists(path):
            print(f"\n  MISSING {label}: {path}")
            if "background" in path:
                print("\n  Download the track from:")
                print("  https://pixabay.com/music/corporate-corporate-background-music-quiet-progress-507151/")
                print(f"\n  Save the MP3 as:\n  {path}")
            sys.exit(1)
        dur = ff_duration(path)
        print(f"  {label}: {dur:.2f}s  {path}")

    print()

    for vname_in, vname_out in VIDEOS:
        vin  = os.path.join(OUTDIR, vname_in)
        vout = os.path.join(OUTDIR, vname_out)

        if not os.path.exists(vin):
            print(f"  SKIP (not found): {vin}")
            continue

        print(f"  Mixing -> {vname_out} ...")
        mix(vin, vout)

        dur      = ff_duration(vout)
        w, h     = verify_stream(vout)
        kb       = os.path.getsize(vout) // 1024
        dim_ok   = "OK" if (w, h) in [(1920, 1080), (1080, 1920)] else "MISMATCH"
        print(f"  {w}x{h} [{dim_ok}]  {dur:.2f}s  {kb:,} KB")

    print("\n" + "=" * 56)
    print("  Done — local preview only, not published.")
    print("=" * 56)
    print("\nAudio rights:")
    print("  Voice: Microsoft David Desktop (Windows SAPI / Windows licence)")
    print("  Music: Pixabay Content License — commercial use permitted,")
    print("         no attribution required. See MUSIC_LICENSE.md.")


if __name__ == "__main__":
    main()
